### ISSUE TITLE
OAuth for Helix endpoints

### ISSUE THREAD

**Issue by keithslater** [nicklaw5/twitch-api-php#58] opened 2020-05-30 01:26 UTC
As of May 1st, it appears Twitch is requiring OAuth authentication for their Helix endpoints. Is there any plan for this project to support that?

https://discuss.dev.twitch.tv/t/requiring-oauth-for-helix-twitch-api-endpoints/23916

**Comment by nicklaw5** [comment] 2020-05-30 18:11
Duplicate of #55

**Closed by nicklaw5** 2020-05-30 18:11 UTC
